# Generated by carnix 0.10.0: carnix generate-nix --standalone --src ./.
with import <nixpkgs> {};
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
  cratesIO = (callPackage ./crates-io.nix { });
in
rec {
  crates = cratesIO // rec {
# rooster-2.8.1

    crates.rooster."2.8.1" = deps: { features?(features_.rooster."2.8.1" deps {}) }: buildRustCrate {
      crateName = "rooster";
      version = "2.8.1";
      description = "A simple password manager for geeks";
      authors = [ "Conrad Kleinespel <conradk@conradk.com>" ];
      src = exclude [ ".git" "target" ] ./.;
      build = "build.rs";
      inherit libsodium;
      dependencies = mapFeatures features ([
        (cratesIO.crates."byteorder"."${deps."rooster"."2.8.1"."byteorder"}" deps)
        (cratesIO.crates."clipboard"."${deps."rooster"."2.8.1"."clipboard"}" deps)
        (cratesIO.crates."dirs"."${deps."rooster"."2.8.1"."dirs"}" deps)
        (cratesIO.crates."getopts"."${deps."rooster"."2.8.1"."getopts"}" deps)
        (cratesIO.crates."libc"."${deps."rooster"."2.8.1"."libc"}" deps)
        (cratesIO.crates."openssl"."${deps."rooster"."2.8.1"."openssl"}" deps)
        (cratesIO.crates."rand"."${deps."rooster"."2.8.1"."rand"}" deps)
        (cratesIO.crates."rpassword"."${deps."rooster"."2.8.1"."rpassword"}" deps)
        (cratesIO.crates."rprompt"."${deps."rooster"."2.8.1"."rprompt"}" deps)
        (cratesIO.crates."serde"."${deps."rooster"."2.8.1"."serde"}" deps)
        (cratesIO.crates."serde_derive"."${deps."rooster"."2.8.1"."serde_derive"}" deps)
        (cratesIO.crates."serde_json"."${deps."rooster"."2.8.1"."serde_json"}" deps)
        (cratesIO.crates."zxcvbn"."${deps."rooster"."2.8.1"."zxcvbn"}" deps)
      ]);
    };
    features_.rooster."2.8.1" = deps: f: updateFeatures f (rec {
      byteorder."${deps.rooster."2.8.1".byteorder}".default = true;
      clipboard."${deps.rooster."2.8.1".clipboard}".default = true;
      dirs."${deps.rooster."2.8.1".dirs}".default = true;
      getopts."${deps.rooster."2.8.1".getopts}".default = true;
      libc."${deps.rooster."2.8.1".libc}".default = true;
      openssl."${deps.rooster."2.8.1".openssl}".default = true;
      rand."${deps.rooster."2.8.1".rand}".default = true;
      rooster."2.8.1".default = (f.rooster."2.8.1".default or true);
      rpassword."${deps.rooster."2.8.1".rpassword}".default = true;
      rprompt."${deps.rooster."2.8.1".rprompt}".default = true;
      serde."${deps.rooster."2.8.1".serde}".default = true;
      serde_derive."${deps.rooster."2.8.1".serde_derive}".default = true;
      serde_json."${deps.rooster."2.8.1".serde_json}".default = true;
      zxcvbn."${deps.rooster."2.8.1".zxcvbn}".default = true;
    }) [
      (cratesIO.features_.byteorder."${deps."rooster"."2.8.1"."byteorder"}" deps)
      (cratesIO.features_.clipboard."${deps."rooster"."2.8.1"."clipboard"}" deps)
      (cratesIO.features_.dirs."${deps."rooster"."2.8.1"."dirs"}" deps)
      (cratesIO.features_.getopts."${deps."rooster"."2.8.1"."getopts"}" deps)
      (cratesIO.features_.libc."${deps."rooster"."2.8.1"."libc"}" deps)
      (cratesIO.features_.openssl."${deps."rooster"."2.8.1"."openssl"}" deps)
      (cratesIO.features_.rand."${deps."rooster"."2.8.1"."rand"}" deps)
      (cratesIO.features_.rpassword."${deps."rooster"."2.8.1"."rpassword"}" deps)
      (cratesIO.features_.rprompt."${deps."rooster"."2.8.1"."rprompt"}" deps)
      (cratesIO.features_.serde."${deps."rooster"."2.8.1"."serde"}" deps)
      (cratesIO.features_.serde_derive."${deps."rooster"."2.8.1"."serde_derive"}" deps)
      (cratesIO.features_.serde_json."${deps."rooster"."2.8.1"."serde_json"}" deps)
      (cratesIO.features_.zxcvbn."${deps."rooster"."2.8.1"."zxcvbn"}" deps)
    ];


# end

  };

  rooster = crates.crates.rooster."2.8.1" deps;
  __all = [ (rooster {}) ];
  deps.aho_corasick."0.6.10" = {
    memchr = "2.2.0";
  };
  deps.aho_corasick."0.7.3" = {
    memchr = "2.2.0";
  };
  deps.argon2rs."0.2.5" = {
    blake2_rfc = "0.2.18";
    scoped_threadpool = "0.1.9";
  };
  deps.arrayvec."0.4.10" = {
    nodrop = "0.1.13";
  };
  deps.autocfg."0.1.2" = {};
  deps.backtrace."0.3.15" = {
    cfg_if = "0.1.7";
    rustc_demangle = "0.1.13";
    autocfg = "0.1.2";
    backtrace_sys = "0.1.28";
    libc = "0.2.51";
    winapi = "0.3.7";
  };
  deps.backtrace_sys."0.1.28" = {
    libc = "0.2.51";
    cc = "1.0.34";
  };
  deps.bit_set."0.4.0" = {
    bit_vec = "0.4.4";
  };
  deps.bit_vec."0.4.4" = {};
  deps.bitflags."1.0.4" = {};
  deps.blake2_rfc."0.2.18" = {
    arrayvec = "0.4.10";
    constant_time_eq = "0.1.3";
  };
  deps.block."0.1.6" = {};
  deps.byteorder."1.3.1" = {};
  deps.cc."1.0.34" = {};
  deps.cfg_if."0.1.7" = {};
  deps.clipboard."0.5.0" = {
    x11_clipboard = "0.3.1";
    objc = "0.2.6";
    objc_foundation = "0.1.1";
    objc_id = "0.1.1";
    clipboard_win = "2.1.2";
  };
  deps.clipboard_win."2.1.2" = {
    winapi = "0.3.7";
  };
  deps.cloudabi."0.0.3" = {
    bitflags = "1.0.4";
  };
  deps.constant_time_eq."0.1.3" = {};
  deps.derive_builder."0.5.1" = {
    derive_builder_core = "0.2.0";
    quote = "0.3.15";
    syn = "0.11.11";
  };
  deps.derive_builder_core."0.2.0" = {
    quote = "0.3.15";
    syn = "0.11.11";
  };
  deps.dirs."1.0.5" = {
    redox_users = "0.3.0";
    libc = "0.2.51";
    winapi = "0.3.7";
  };
  deps.either."1.5.2" = {};
  deps.failure."0.1.5" = {
    backtrace = "0.3.15";
    failure_derive = "0.1.5";
  };
  deps.failure_derive."0.1.5" = {
    proc_macro2 = "0.4.27";
    quote = "0.6.11";
    syn = "0.15.30";
    synstructure = "0.10.1";
  };
  deps.fancy_regex."0.1.0" = {
    bit_set = "0.4.0";
    lazy_static = "0.2.11";
    memchr = "1.0.2";
    regex = "0.2.11";
  };
  deps.foreign_types."0.3.2" = {
    foreign_types_shared = "0.1.1";
  };
  deps.foreign_types_shared."0.1.1" = {};
  deps.fuchsia_cprng."0.1.1" = {};
  deps.getopts."0.2.18" = {
    unicode_width = "0.1.5";
  };
  deps.itertools."0.7.11" = {
    either = "1.5.2";
  };
  deps.itoa."0.4.3" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.lazy_static."0.2.11" = {};
  deps.lazy_static."1.3.0" = {};
  deps.libc."0.2.51" = {};
  deps.log."0.4.6" = {
    cfg_if = "0.1.7";
  };
  deps.malloc_buf."0.0.6" = {
    libc = "0.2.51";
  };
  deps.memchr."1.0.2" = {
    libc = "0.2.51";
  };
  deps.memchr."2.2.0" = {};
  deps.nodrop."0.1.13" = {};
  deps.objc."0.2.6" = {
    malloc_buf = "0.0.6";
  };
  deps.objc_foundation."0.1.1" = {
    block = "0.1.6";
    objc = "0.2.6";
    objc_id = "0.1.1";
  };
  deps.objc_id."0.1.1" = {
    objc = "0.2.6";
  };
  deps.openssl."0.10.20" = {
    bitflags = "1.0.4";
    cfg_if = "0.1.7";
    foreign_types = "0.3.2";
    lazy_static = "1.3.0";
    libc = "0.2.51";
    openssl_sys = "0.9.43";
  };
  deps.openssl_sys."0.9.43" = {
    libc = "0.2.51";
    cc = "1.0.34";
    pkg_config = "0.3.14";
    rustc_version = "0.2.3";
  };
  deps.pkg_config."0.3.14" = {};
  deps.proc_macro2."0.4.27" = {
    unicode_xid = "0.1.0";
  };
  deps.quick_error."1.2.2" = {};
  deps.quote."0.3.15" = {};
  deps.quote."0.6.11" = {
    proc_macro2 = "0.4.27";
  };
  deps.rand."0.6.5" = {
    rand_chacha = "0.1.1";
    rand_core = "0.4.0";
    rand_hc = "0.1.0";
    rand_isaac = "0.1.1";
    rand_jitter = "0.1.3";
    rand_os = "0.1.3";
    rand_pcg = "0.1.2";
    rand_xorshift = "0.1.1";
    autocfg = "0.1.2";
    libc = "0.2.51";
    winapi = "0.3.7";
  };
  deps.rand_chacha."0.1.1" = {
    rand_core = "0.3.1";
    autocfg = "0.1.2";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.0";
  };
  deps.rand_core."0.4.0" = {};
  deps.rand_hc."0.1.0" = {
    rand_core = "0.3.1";
  };
  deps.rand_isaac."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rand_jitter."0.1.3" = {
    rand_core = "0.4.0";
    libc = "0.2.51";
    winapi = "0.3.7";
  };
  deps.rand_os."0.1.3" = {
    rand_core = "0.4.0";
    rdrand = "0.4.0";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.51";
    winapi = "0.3.7";
  };
  deps.rand_pcg."0.1.2" = {
    rand_core = "0.4.0";
    autocfg = "0.1.2";
  };
  deps.rand_xorshift."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.redox_syscall."0.1.53" = {};
  deps.redox_users."0.3.0" = {
    argon2rs = "0.2.5";
    failure = "0.1.5";
    rand_os = "0.1.3";
    redox_syscall = "0.1.53";
  };
  deps.regex."0.2.11" = {
    aho_corasick = "0.6.10";
    memchr = "2.2.0";
    regex_syntax = "0.5.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex."1.1.5" = {
    aho_corasick = "0.7.3";
    memchr = "2.2.0";
    regex_syntax = "0.6.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex_syntax."0.5.6" = {
    ucd_util = "0.1.3";
  };
  deps.regex_syntax."0.6.6" = {
    ucd_util = "0.1.3";
  };
  deps.rooster."2.8.1" = {
    byteorder = "1.3.1";
    clipboard = "0.5.0";
    dirs = "1.0.5";
    getopts = "0.2.18";
    libc = "0.2.51";
    openssl = "0.10.20";
    rand = "0.6.5";
    rpassword = "3.0.1";
    rprompt = "1.0.3";
    serde = "1.0.90";
    serde_derive = "1.0.90";
    serde_json = "1.0.39";
    zxcvbn = "1.0.1";
  };
  deps.rpassword."3.0.1" = {
    libc = "0.2.51";
    kernel32_sys = "0.2.2";
    winapi = "0.2.8";
  };
  deps.rprompt."1.0.3" = {};
  deps.rustc_demangle."0.1.13" = {};
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.ryu."0.2.7" = {};
  deps.scoped_threadpool."0.1.9" = {};
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.serde."1.0.90" = {};
  deps.serde_derive."1.0.90" = {
    proc_macro2 = "0.4.27";
    quote = "0.6.11";
    syn = "0.15.30";
  };
  deps.serde_json."1.0.39" = {
    itoa = "0.4.3";
    ryu = "0.2.7";
    serde = "1.0.90";
  };
  deps.syn."0.11.11" = {
    quote = "0.3.15";
    synom = "0.11.3";
    unicode_xid = "0.0.4";
  };
  deps.syn."0.15.30" = {
    proc_macro2 = "0.4.27";
    quote = "0.6.11";
    unicode_xid = "0.1.0";
  };
  deps.synom."0.11.3" = {
    unicode_xid = "0.0.4";
  };
  deps.synstructure."0.10.1" = {
    proc_macro2 = "0.4.27";
    quote = "0.6.11";
    syn = "0.15.30";
    unicode_xid = "0.1.0";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.3.0";
  };
  deps.time."0.1.42" = {
    libc = "0.2.51";
    redox_syscall = "0.1.53";
    winapi = "0.3.7";
  };
  deps.ucd_util."0.1.3" = {};
  deps.unicode_width."0.1.5" = {};
  deps.unicode_xid."0.0.4" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.utf8_ranges."1.0.2" = {};
  deps.vcpkg."0.2.6" = {};
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.x11_clipboard."0.3.1" = {
    xcb = "0.8.2";
  };
  deps.xcb."0.8.2" = {
    libc = "0.2.51";
    log = "0.4.6";
  };
  deps.zxcvbn."1.0.1" = {
    derive_builder = "0.5.1";
    fancy_regex = "0.1.0";
    itertools = "0.7.11";
    lazy_static = "1.3.0";
    quick_error = "1.2.2";
    regex = "1.1.5";
    time = "0.1.42";
  };
}
